apiVersion : apps/v1
kind: Deployment
metadata:
  name: p2bk 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2bk
  template:
    metadata:
      labels:
        app: p2bk 
    spec:
      containers:
        - name: p2bk 
          image: p2teamacr.azurecr.io/p2bk:82
          env:
          - name : DB_URL
            valueFrom: 
              secretKeyRef:
                name: db-credentials
                key: DB_URL
          - name : DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key : DB_USERNAME
          - name : DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PORT
