apiVersion : apps/v1
kind: Deployment
metadata:
  name: bk 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bk
  template:
    metadata:
      labels:
        app: bk 
    spec:
      containers:
        - name: bk 
          image: acrteam4.azurecr.io/bk:61
          env:
          - name : DB_URL
            valueFrom: 
              secretKeyRef:
                name: db-credentials
                key: DB_URL
          - name : DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key : DB_USERNAME
          - name : DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PORT
